# fly.toml app configuration file generated for steve-agent on 2025-01-16T12:12:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'steve-agent'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
